# Generated by Django 4.2.11 on 2024-04-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Kurulma Tarihi'),
        ),
        migrations.AddField(
            model_name='personel',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Kurulma Tarihi'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Kurulma Tarihi'),
        ),
    ]
