# Generated by Django 4.2.11 on 2024-04-28 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_payments_created_at_personel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('city', models.CharField(max_length=155, verbose_name='Şehir')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Sirket')),
            ],
        ),
        migrations.CreateModel(
            name='Activitycost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ücreti')),
                ('currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('RMB', 'RMB (人民币)')], max_length=3, verbose_name='Para Birimi')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.activity', verbose_name='Activite')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Sirket')),
            ],
        ),
        migrations.CreateModel(
            name='Activitysupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('contact', models.CharField(max_length=155, verbose_name='İletişim')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Sirket')),
            ],
        ),
        migrations.CreateModel(
            name='Buyercompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('short_name', models.CharField(max_length=5, unique=True, verbose_name='Kısa adı')),
                ('contact', models.CharField(blank=True, max_length=155, null=True, verbose_name='İletişim')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Sirket')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maliyet Binek')),
                ('minivan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maliyet Minivan')),
                ('minibus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maliyet Minibüs')),
                ('midibus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maliyet Midibüs')),
                ('bus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maliyet Otobüs')),
                ('currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('RMB', 'RMB (人民币)')], default='TL', max_length=3, verbose_name='Para Birimi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Sirket')),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Adı')),
                ('city', models.CharField(max_length=155, verbose_name='Şehir')),
                ('doc_no', models.CharField(blank=True, max_length=155, null=True, verbose_name='Rehber No')),
                ('phone', models.CharField(max_length=155, verbose_name='Telefon No')),
                ('mail', models.CharField(blank=True, max_length=155, null=True, verbose_name='Mail')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ücreti')),
                ('currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('RMB', 'RMB (人民币)')], default='TL', max_length=3, verbose_name='Para Birimi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Sirket')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('city', models.CharField(max_length=155, verbose_name='Şehir')),
                ('mail', models.CharField(blank=True, max_length=155, null=True, verbose_name='Mail')),
                ('one_person', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tek Kişilik Ücreti')),
                ('two_person', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İki Kişilik Ücreti')),
                ('tree_person', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Üç Kişilik Ücreti')),
                ('finish', models.DateField(blank=True, null=True, verbose_name='Fiyat Geçerlilik Tarihi')),
                ('currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('RMB', 'RMB (人民币)')], default='TL', max_length=3, verbose_name='Para Birimi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Sirket')),
            ],
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('city', models.CharField(max_length=155, verbose_name='Şehir')),
                ('contact', models.CharField(max_length=155, verbose_name='İletişim')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ücreti')),
                ('currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('RMB', 'RMB (人民币)')], max_length=3, verbose_name='Para Birimi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Sirket')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Adı')),
                ('contact', models.CharField(max_length=155, verbose_name='İletişim')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Sirket')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=155, verbose_name='Güzergah')),
                ('sellcar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Araç Satış Fiyatı')),
                ('sellminivan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minivan Satış')),
                ('sellminibus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minibüs Satış')),
                ('sellmidibus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Midibüs Satış')),
                ('sellbus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Otobüs Satış')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Sirket')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=155, verbose_name='Güzergah')),
                ('sellcar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Binek Satış Fiyatı')),
                ('sellminivan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minivan Satış Fiyatı')),
                ('sellminibus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minibüs Satış Fiyatı')),
                ('sellmidibus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Midibüs Satış Fiyatı')),
                ('sellbus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Otobüs Satış Fiyatı')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Sirket')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=155, verbose_name='Araçlar')),
                ('capacity', models.PositiveIntegerField(verbose_name='Kapasite')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Sirket')),
            ],
        ),
        migrations.AlterField(
            model_name='personel',
            name='job',
            field=models.CharField(choices=[('Satış Personeli', 'Satış Personeli'), ('Operasyon Şefi', 'Operasyon Şefi'), ('Yönetim', 'Yönetim'), ('Muhasebe', 'Muhasebe'), ('Sistem Geliştiricisi', 'Sistem Geliştiricisi')], default='Satış Personeli', max_length=20, verbose_name='Görevi'),
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.AddField(
            model_name='cost',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.supplier', verbose_name='Tedarikçi'),
        ),
        migrations.AddField(
            model_name='cost',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.tour', verbose_name='Tur'),
        ),
        migrations.AddField(
            model_name='cost',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.transfer', verbose_name='Transfer'),
        ),
        migrations.AddField(
            model_name='activitycost',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.activitysupplier', verbose_name='Aktivite Tedarikçisi'),
        ),
    ]
