# Generated by Django 4.2.11 on 2024-04-28 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_personel_dark_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Şirket (公司)')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.personel', verbose_name='Personel')),
            ],
        ),
    ]
