# Generated by Django 4.2.11 on 2024-04-29 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_activitycost_currency_alter_museum_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('ticket', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Tur Etiketi')),
                ('start', models.DateField(verbose_name='Başlama Tarihi')),
                ('finish', models.DateField(verbose_name='Bitiş Tarihi')),
                ('passenger_info', models.TextField(verbose_name='Yolcu Bilgileri')),
                ('number_passengers', models.PositiveIntegerField(default=1, verbose_name='Yolcu Sayısı')),
                ('payment_type', models.CharField(blank=True, choices=[('Pesin', 'Peşin'), ('Taksitli', 'Taksitli'), ('Parcalı', 'Parçalı')], max_length=20, null=True, verbose_name='Ödeme Türü')),
                ('payment_channel', models.CharField(blank=True, choices=[('Havale', 'Havale'), ('Xctrip', 'Xctrip')], max_length=20, null=True, verbose_name='Ödeme Kanalı')),
                ('remaining_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kalan Ödeme')),
                ('tl_sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TL Satış Fiyatı')),
                ('usd_sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='USD Satış Fiyatı')),
                ('eur_sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='EUR Satış Fiyatı')),
                ('rbm_sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RBM Satış Fiyatı')),
                ('tl_cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TL Maliyet Fiyatı')),
                ('usd_cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='USD Maliyet Fiyatı')),
                ('eur_cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='EUR Maliyet Fiyatı')),
                ('rbm_cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RBM Maliyet Fiyatı')),
                ('buyer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Alıcı', to='Core.buyercompany', verbose_name='Alıcı Firma')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Şirket')),
                ('follow_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Takip', to='Core.personel', verbose_name='Takip Eden Personel')),
                ('selling_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Satan', to='Core.personel', verbose_name='Satan Personel')),
            ],
        ),
        migrations.CreateModel(
            name='Operationday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Şirket')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.operation', verbose_name='Operasyon')),
            ],
        ),
        migrations.CreateModel(
            name='Operationitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('Transfer', 'Transfer'), ('Tur', 'Tur'), ('TurTransfer', 'Tur + Transfer'), ('TransferTur', 'Transfer + Tur'), ('Arac', 'Araç'), ('Aktivite', 'Aktivite'), ('Muze', 'Müze'), ('Otel', 'Otel'), ('Rehber', 'Rehber'), ('Aracli Rehber', 'Araçlı Rehber'), ('Serbest Zaman', 'Serbest Zaman')], max_length=20, verbose_name='İşlem Türü')),
                ('pick_time', models.TimeField(blank=True, null=True, verbose_name='Alış Saati')),
                ('release_time', models.TimeField(blank=True, null=True, verbose_name='Bırakış Saati')),
                ('release_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bırakış Yeri')),
                ('pick_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alış Yeri')),
                ('vehicle_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Araç Ücreti')),
                ('room_type', models.CharField(blank=True, choices=[('Tek', 'Tek'), ('Cift', 'Çift'), ('Uc', 'Üç')], max_length=20, null=True, verbose_name='Oda Türü')),
                ('hotel_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Otel Ücreti')),
                ('hotel_currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('RMB', 'RMB')], default='USD', max_length=3, verbose_name='Otel Para Birimi')),
                ('activity_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aktivite Ücreti')),
                ('activity_currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('RMB', 'RMB')], default='USD', max_length=3, verbose_name='Aktivite Para Birimi')),
                ('museum_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Müze Ücreti')),
                ('museum_currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('RMB', 'RMB')], default='USD', max_length=3, verbose_name='Müze Para Birimi')),
                ('driver', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şoför')),
                ('driver_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şoför Telefon')),
                ('plaka', models.CharField(blank=True, max_length=255, null=True, verbose_name='Plaka')),
                ('guide_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rehber Ücreti')),
                ('guide_currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('RMB', 'RMB')], default='USD', max_length=3, verbose_name='Rehber Para Birimi')),
                ('other_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Diğer Ücretler')),
                ('other_currency', models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('RMB', 'RMB')], default='USD', max_length=3, verbose_name='Diğer Ücretler Para Birimi')),
                ('tl_cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TL Maliyet Fiyatı')),
                ('usd_cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='USD Maliyet Fiyatı')),
                ('eur_cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='EUR Maliyet Fiyatı')),
                ('rbm_cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RMB Maliyet Fiyatı')),
                ('description', models.TextField(verbose_name='Tur Detayı')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.activity', verbose_name='Aktivite')),
                ('activity_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.activitysupplier', verbose_name='Aktivite Tedarikçi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Şirket')),
                ('cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.cost', verbose_name='Araç Maaliyet')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.operationday', verbose_name='Gün')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.guide', verbose_name='Rehber')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.hotel', verbose_name='Otel')),
                ('new_museum', models.ManyToManyField(blank=True, related_name='new_operation_items', to='Core.museum', verbose_name='Müzeler')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.supplier', verbose_name='Araç Tedarikçi')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.tour', verbose_name='Tur')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.transfer', verbose_name='Transfer')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.vehicle', verbose_name='Araç')),
            ],
        ),
    ]
