# Generated by Django 4.2.11 on 2024-05-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_operation_operationday_operationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tur Detayı'),
        ),
    ]
