# Generated by Django 4.2.11 on 2024-05-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_alter_operationitem_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationitem',
            old_name='activity_cost',
            new_name='activity_supplier',
        ),
    ]
