# Generated by Django 4.2.11 on 2024-05-06 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_rename_activity_cost_operationitem_activity_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycost',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.activity', verbose_name='Activite'),
        ),
        migrations.AlterField(
            model_name='activitycost',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.activitysupplier', verbose_name='Aktivite Tedarikçisi'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.supplier', verbose_name='Tedarikçi'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.tour', verbose_name='Tur'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.transfer', verbose_name='Transfer'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='buyer_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Alıcı', to='Core.buyercompany', verbose_name='Alıcı Firma'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='follow_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Takip', to='Core.personel', verbose_name='Takip Eden Personel'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='selling_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Satan', to='Core.personel', verbose_name='Satan Personel'),
        ),
        migrations.AlterField(
            model_name='operationitem',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.activity', verbose_name='Aktivite'),
        ),
        migrations.AlterField(
            model_name='operationitem',
            name='activity_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.activitysupplier', verbose_name='Aktivite Tedarikçi'),
        ),
        migrations.AlterField(
            model_name='operationitem',
            name='cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.cost', verbose_name='Araç Maaliyet'),
        ),
        migrations.AlterField(
            model_name='operationitem',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.guide', verbose_name='Rehber'),
        ),
        migrations.AlterField(
            model_name='operationitem',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.hotel', verbose_name='Otel'),
        ),
        migrations.AlterField(
            model_name='operationitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.supplier', verbose_name='Araç Tedarikçi'),
        ),
        migrations.AlterField(
            model_name='operationitem',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.tour', verbose_name='Tur'),
        ),
        migrations.AlterField(
            model_name='operationitem',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.transfer', verbose_name='Transfer'),
        ),
        migrations.AlterField(
            model_name='operationitem',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.vehicle', verbose_name='Araç'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.personel', verbose_name='Personel'),
        ),
    ]
