# Generated by Django 4.2.11 on 2024-05-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_alter_activitycost_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationitem',
            name='activity_payment',
            field=models.BooleanField(default=False, verbose_name='Aktivite Ücreti Bizde'),
        ),
        migrations.AddField(
            model_name='operationitem',
            name='hotel_payment',
            field=models.BooleanField(default=False, verbose_name='Otel Ücreti Bizde'),
        ),
        migrations.AddField(
            model_name='operationitem',
            name='museum_payment',
            field=models.BooleanField(default=False, verbose_name='Müze Ücreti Bizde'),
        ),
    ]
