# Generated by Django 4.2.11 on 2024-05-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_operationitem_activity_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationitem',
            name='activity_payment',
            field=models.CharField(choices=[('Evet', 'Evet'), ('Hayır', 'Hayır')], default='Hayır', max_length=20, verbose_name='Activite Ödemesi'),
        ),
        migrations.AlterField(
            model_name='operationitem',
            name='hotel_payment',
            field=models.CharField(choices=[('Evet', 'Evet'), ('Hayır', 'Hayır')], default='Hayır', max_length=20, verbose_name='Otel Ödemesi'),
        ),
        migrations.AlterField(
            model_name='operationitem',
            name='museum_payment',
            field=models.CharField(choices=[('Evet', 'Evet'), ('Hayır', 'Hayır')], default='Hayır', max_length=20, verbose_name='Müze Ödemesi'),
        ),
    ]
