# Generated by Django 4.2.11 on 2024-05-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0017_operationitem_activity_cost_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationitem',
            name='vehicle_currency',
            field=models.CharField(choices=[('TL', 'TL'), ('USD', 'USD'), ('EUR', 'EUR'), ('RMB', 'RMB')], default='USD', max_length=3, verbose_name='Araç Para Birimi'),
        ),
    ]
