# Generated by Django 4.2.11 on 2024-05-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_operationitem_vehicle_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationitem',
            name='museum_person',
            field=models.IntegerField(default=0, verbose_name='Müze Kişi Sayısı'),
        ),
    ]
