# Generated by Django 4.2.11 on 2024-05-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0019_operationitem_museum_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationitem',
            old_name='rbm_cost_price',
            new_name='rmb_cost_price',
        ),
    ]
