# Generated by Django 4.2.11 on 2024-05-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0020_rename_rbm_cost_price_operationitem_rmb_cost_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationitem',
            name='rmb_cost_price',
        ),
    ]
