# Generated by Django 4.2.11 on 2024-05-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0021_remove_operationitem_rmb_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationitem',
            name='rmb_cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RMB Maliyet Fiyatı'),
        ),
    ]
