# Generated by Django 4.2.11 on 2024-05-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0022_operationitem_rmb_cost_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationitem',
            name='rmb_cost_price',
        ),
    ]
