# Generated by Django 4.2.11 on 2024-05-07 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0024_operationitem_rmb_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('recipients_group', models.CharField(choices=[('Herkes', 'Herkes'), ('Satış Personeli', 'Satış Personeli'), ('Operasyon Şefi', 'Operasyon Şefi'), ('Yönetim', 'Yönetim'), ('Muhasebe', 'Muhasebe')], default='Herkes', max_length=20, verbose_name='Mesaj Grupları')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='Core.personel')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='Core.notification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='Core.personel')),
            ],
            options={
                'unique_together': {('notification', 'recipient')},
            },
        ),
    ]
