# Generated by Django 4.2.11 on 2024-05-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0026_notification_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Şablon Adı')),
                ('day_numbers', models.IntegerField(verbose_name='Gün Sayısı')),
                ('tl_sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TL Satış Fiyatı')),
                ('usd_sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='USD Satış Fiyatı')),
                ('eur_sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='EUR Satış Fiyatı')),
                ('rbm_sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RBM Satış Fiyatı')),
                ('buyer_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.buyercompany', verbose_name='Alıcı Firma')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Şirket')),
            ],
        ),
        migrations.CreateModel(
            name='OperationitemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('Transfer', 'Transfer'), ('Tur', 'Tur'), ('TurTransfer', 'Tur + Transfer'), ('TransferTur', 'Transfer + Tur'), ('Arac', 'Araç'), ('Aktivite', 'Aktivite'), ('Muze', 'Müze'), ('Otel', 'Otel'), ('Rehber', 'Rehber'), ('Aracli Rehber', 'Araçlı Rehber'), ('Serbest Zaman', 'Serbest Zaman')], max_length=20, verbose_name='İşlem Türü')),
                ('pick_time', models.TimeField(blank=True, null=True, verbose_name='Alış Saati')),
                ('release_time', models.TimeField(blank=True, null=True, verbose_name='Bırakış Saati')),
                ('room_type', models.CharField(blank=True, choices=[('Tek', 'Tek'), ('Cift', 'Çift'), ('Uc', 'Üç')], max_length=20, null=True, verbose_name='Oda Türü')),
                ('hotel_payment', models.CharField(choices=[('Evet', 'Evet'), ('Hayır', 'Hayır')], default='Hayır', max_length=20, verbose_name='Otel Ödemesi Bizde')),
                ('activity_payment', models.CharField(choices=[('Evet', 'Evet'), ('Hayır', 'Hayır')], default='Hayır', max_length=20, verbose_name='Activite Ödemesi Bizde')),
                ('museum_payment', models.CharField(choices=[('Evet', 'Evet'), ('Hayır', 'Hayır')], default='Hayır', max_length=20, verbose_name='Müze Ödemesi Bizde')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tur Detayı')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.activity', verbose_name='Aktivite')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Şirket')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.hotel', verbose_name='Otel')),
                ('new_museum', models.ManyToManyField(blank=True, to='Core.museum', verbose_name='Müzeler')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.operationtemplate', verbose_name='Operasyon Şablonu')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.tour', verbose_name='Tur')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.transfer', verbose_name='Transfer')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.vehicle', verbose_name='Araç')),
            ],
        ),
    ]
