# Generated by Django 4.2.11 on 2024-05-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0027_operationtemplate_operationitemtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationitemtemplate',
            name='day_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kaçıncı Gün'),
        ),
    ]
