# Generated by Django 4.2.11 on 2024-05-09 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0028_operationitemtemplate_day_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationdayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.sirket', verbose_name='Şirket')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.operation', verbose_name='Operasyon')),
            ],
        ),
    ]
