# Generated by Django 4.2.11 on 2024-05-09 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0030_remove_operationitemtemplate_day_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationdaytemplate',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.operationtemplate', verbose_name='Operasyon Şablonu'),
        ),
    ]
