# Generated by Django 4.2.11 on 2024-05-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0031_alter_operationdaytemplate_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationdaytemplate',
            name='date',
        ),
        migrations.RemoveField(
            model_name='operationitemtemplate',
            name='day',
        ),
        migrations.AddField(
            model_name='operationdaytemplate',
            name='day_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gün Numarası'),
        ),
        migrations.AddField(
            model_name='operationitemtemplate',
            name='day_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Aktif Olduğu Gün Numarası'),
        ),
    ]
