# Generated by Django 4.2.11 on 2024-05-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0034_operationitem_guide_var'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='contact',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='İletişim'),
        ),
    ]
