# Generated by Django 4.2.11 on 2024-05-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0036_exchangerate"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="eur_activity_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="EUR Aktivite Fiyatı",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="rbm_activity_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="RBM Aktivite Fiyatı",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="tl_activity_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="TL Aktivite Fiyatı",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="usd_activity_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="USD Aktivite Fiyatı",
            ),
        ),
    ]
