# Generated by Django 4.2.11 on 2024-05-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0037_operation_eur_activity_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="cevap",
            field=models.TextField(blank=True, null=True, verbose_name="Cevap"),
        ),
    ]
