# Generated by Django 4.2.11 on 2024-05-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0038_supportticket_cevap"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="activitycost",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="activitysupplier",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="buyercompany",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="cost",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="guide",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="museum",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="personel",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="sirket",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="tour",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="transfer",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
    ]
