# Generated by Django 4.2.11 on 2024-05-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0039_activity_is_delete_activitycost_is_delete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="operationday",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
        migrations.AddField(
            model_name="operationitem",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
    ]
