# Generated by Django 4.2.11 on 2024-05-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0041_sell_activitysell"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitysell",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Satış Fiyatı",
            ),
        ),
        migrations.AlterField(
            model_name="sell",
            name="bus",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Satış Otobüs",
            ),
        ),
        migrations.AlterField(
            model_name="sell",
            name="car",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Satış Binek",
            ),
        ),
        migrations.AlterField(
            model_name="sell",
            name="midibus",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Satış Midibüs",
            ),
        ),
        migrations.AlterField(
            model_name="sell",
            name="minibus",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Satış Minibüs",
            ),
        ),
        migrations.AlterField(
            model_name="sell",
            name="minivan",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Satış Minivan",
            ),
        ),
    ]
