# Generated by Django 4.2.11 on 2024-05-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0042_alter_activitysell_price_alter_sell_bus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationitem",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
    ]
