# Generated by Django 4.2.11 on 2024-05-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0043_operationitem_is_processed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationitem",
            name="museum_person",
            field=models.IntegerField(default=0, verbose_name="Kişi Sayısı"),
        ),
    ]
