# Generated by Django 4.2.11 on 2024-05-27 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0044_alter_operationitem_museum_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Zamanı"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Zamanı"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.sirket",
                        verbose_name="Sirket",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alicilar",
                        to="Core.personel",
                        verbose_name="Alıcılar",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gonderen",
                        to="Core.personel",
                        verbose_name="Gönderen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesaj Logu",
                "verbose_name_plural": "Mesaj Logları",
            },
        ),
    ]
