# Generated by Django 4.2.11 on 2024-05-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0046_rename_smslog_smsgonder"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsgonder",
            name="is_delete",
            field=models.BooleanField(default=False, verbose_name="Silindi mi?"),
        ),
    ]
