# Generated by Django 4.2.11 on 2024-05-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0047_smsgonder_is_delete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tour",
            name="sellbus",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="sellcar",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="sellmidibus",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="sellminibus",
        ),
        migrations.RemoveField(
            model_name="tour",
            name="sellminivan",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="sellbus",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="sellcar",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="sellmidibus",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="sellminibus",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="sellminivan",
        ),
    ]
