# Generated by Django 4.2.11 on 2024-05-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0049_chatroom_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="room",
        ),
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
