# Generated by Django 4.2.11 on 2024-06-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0051_chatroom_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationitem",
            name="auto_vehicle_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Araç Ücreti"
            ),
        ),
        migrations.AddField(
            model_name="operationitem",
            name="manuel_vehicle_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Hesaplanan Araç Ücreti",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Core.supplier",
                verbose_name="Manuel Araç Tedarikçi",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="vehicle_currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR"), ("RMB", "RMB")],
                default="TL",
                max_length=3,
                verbose_name="Araç Para Birimi",
            ),
        ),
    ]
