# Generated by Django 4.2.11 on 2024-06-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0053_alter_operationitem_auto_vehicle_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="sold",
            field=models.BooleanField(default=False, verbose_name="Satıldı"),
        ),
    ]
