# Generated by Django 4.2.11 on 2024-06-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0057_alter_operation_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="payment_channel",
            field=models.CharField(
                blank=True,
                choices=[("Havale", "Havale"), ("Xctrip", "Xctrip")],
                default=None,
                max_length=20,
                null=True,
                verbose_name="Ödeme Kanalı",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pesin", "Peşin"),
                    ("Taksitli", "Taksitli"),
                    ("Parcalı", "Parçalı"),
                ],
                default=None,
                max_length=20,
                null=True,
                verbose_name="Ödeme Türü",
            ),
        ),
    ]
