# Generated by Django 4.2.11 on 2024-06-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0058_alter_operation_payment_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="sold",
            field=models.CharField(
                blank=True,
                choices=[("sold", "Satıldı"), ("notsold", "Satılmadı")],
                default="sold",
                max_length=20,
                null=True,
                verbose_name="Satıldı",
            ),
        ),
    ]
