# Generated by Django 4.2.11 on 2024-06-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0060_alter_operation_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="sold",
            field=models.CharField(
                blank=True,
                choices=[("Istendi", "Istendi"), ("Alındı", "Alındı")],
                default="Istendi",
                max_length=20,
                null=True,
                verbose_name="Ödeme Durumu",
            ),
        ),
    ]
