# Generated by Django 4.2.11 on 2024-06-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0064_alter_operation_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="action",
            field=models.CharField(max_length=355),
        ),
    ]
