# Generated by Django 4.2.11 on 2024-06-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0065_alter_useractivitylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="total_cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Toplam Maliyet Fiyatı",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="total_sales_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Toplam Satış Fiyatı",
            ),
        ),
    ]
