# Generated by Django 4.2.11 on 2024-06-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0066_operation_total_cost_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationitem",
            name="auto_activity_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Hesaplanan Aktivite Ücreti",
            ),
        ),
        migrations.AddField(
            model_name="operationitem",
            name="manuel_activity_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Manuel Aktivite Ücreti",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="activity_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Kayıtlı Aktivite Ücreti",
            ),
        ),
    ]
