# Generated by Django 4.2.11 on 2024-06-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0067_operationitem_auto_activity_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="action",
            field=models.CharField(max_length=1024),
        ),
    ]
