# Generated by Django 4.2.11 on 2024-06-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0068_alter_useractivitylog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="action",
            field=models.TextField(),
        ),
    ]
