# Generated by Django 4.2.11 on 2024-06-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0069_alter_useractivitylog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationitem",
            name="activity_sell_currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR"), ("RMB", "RMB")],
                default="USD",
                max_length=3,
                verbose_name="Aktivite Satış Birimi",
            ),
        ),
        migrations.AddField(
            model_name="operationitem",
            name="activity_sell_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Aktivite Satış Ücreti",
            ),
        ),
        migrations.AddField(
            model_name="operationitem",
            name="guide_sell_currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR"), ("RMB", "RMB")],
                default="USD",
                max_length=3,
                verbose_name="Rehber Satış Birimi",
            ),
        ),
        migrations.AddField(
            model_name="operationitem",
            name="guide_sell_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Rehber Satış Ücreti",
            ),
        ),
        migrations.AddField(
            model_name="operationitem",
            name="hotel_sell_currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR"), ("RMB", "RMB")],
                default="USD",
                max_length=3,
                verbose_name="Otel Satış Birimi",
            ),
        ),
        migrations.AddField(
            model_name="operationitem",
            name="hotel_sell_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Otel Satış Ücreti",
            ),
        ),
        migrations.AddField(
            model_name="operationitem",
            name="museum_sell_currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR"), ("RMB", "RMB")],
                default="USD",
                max_length=3,
                verbose_name="Müze Satış Birimi",
            ),
        ),
        migrations.AddField(
            model_name="operationitem",
            name="museum_sell_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Müze Satış Ücreti",
            ),
        ),
        migrations.AddField(
            model_name="operationitem",
            name="vehicle_sell_currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR"), ("RMB", "RMB")],
                default="TL",
                max_length=3,
                verbose_name="Araç Satış Birimi",
            ),
        ),
        migrations.AddField(
            model_name="operationitem",
            name="vehicle_sell_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Araç Satış Ücreti",
            ),
        ),
    ]
