# Generated by Django 4.2.11 on 2024-06-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0073_alter_activitysell_currency_cari"),
    ]

    operations = [
        migrations.AddField(
            model_name="cari",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Açıklama"),
        ),
    ]
