# Generated by Django 4.2.11 on 2024-06-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0075_cari_activity_supplier_cari_buyer_company_cari_hotel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cari",
            name="guide",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rehber_gider",
                to="Core.guide",
                verbose_name="Rehberler",
            ),
        ),
    ]
