# Generated by Django 4.2.11 on 2024-07-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0077_cari_is_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationitem",
            name="vehicle_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Araç Ücreti",
            ),
        ),
    ]
