# Generated by Django 4.2.11 on 2024-07-28 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0078_alter_operationitem_vehicle_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Konum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route", models.CharField(max_length=155, verbose_name="Konum")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Silindi mi?"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.sirket",
                        verbose_name="Sirket",
                    ),
                ),
            ],
        ),
    ]
