# Generated by Django 4.2.11 on 2024-07-28 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0079_konum"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Silindi mi?"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.sirket",
                        verbose_name="Sirket",
                    ),
                ),
                (
                    "konum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.konum",
                        verbose_name="Konum",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.transfer",
                        verbose_name="Tur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TourRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Silindi mi?"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.sirket",
                        verbose_name="Sirket",
                    ),
                ),
                (
                    "konum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.konum",
                        verbose_name="Konum",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.tour",
                        verbose_name="Tur",
                    ),
                ),
            ],
        ),
    ]
