# Generated by Django 4.2.11 on 2024-07-30 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0080_transferroute_tourroute"),
    ]

    operations = [
        migrations.AddField(
            model_name="guide",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Core.konum",
                verbose_name="Location",
            ),
        ),
    ]
