# Generated by Django 4.2.11 on 2024-07-30 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0081_guide_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Core.konum",
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Core.konum",
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="museum",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Core.konum",
                verbose_name="Location",
            ),
        ),
    ]
