# Generated by Django 4.2.11 on 2024-08-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0082_activity_location_hotel_location_museum_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="sirket",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="company_logos/", verbose_name="Logo"
            ),
        ),
        migrations.AddField(
            model_name="sirket",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AddField(
            model_name="sirket",
            name="updated_at",
            field=models.DateField(auto_now=True, verbose_name="Güncelleme Tarihi"),
        ),
    ]
