# Generated by Django 4.2.11 on 2024-08-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0087_hotel_new_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("demo", "Demo"),
                            ("basic", "Basic"),
                            ("team", "Team"),
                            ("professional", "Professional"),
                        ],
                        max_length=20,
                        verbose_name="Plan Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Monthly Price",
                    ),
                ),
                (
                    "yearly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Yearly Price",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Updated At"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
            ],
        ),
    ]
