# Generated by Django 4.2.11 on 2024-08-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0090_personel_gender_vehiclesuppliercities_vehiclecost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salesprice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Ücreti",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR")],
                        default="TL",
                        max_length=3,
                        verbose_name="Para Birimi",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Silindi mi?"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.sirket",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="Core.operation",
                        verbose_name="Opetaion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Müşteri Adı")),
                (
                    "pasaport",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Pasaport Numarası",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Telefon Numarası",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Doğum Tarihi")),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Silindi mi?"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Core.sirket",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="Core.operation",
                        verbose_name="Opetaion",
                    ),
                ),
            ],
        ),
    ]
