# Generated by Django 4.2.11 on 2024-08-25 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0091_salesprice_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationday",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="Core.operation",
                verbose_name="Operasyon",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="Core.operationday",
                verbose_name="Gün",
            ),
        ),
    ]
