# Generated by Django 4.2.11 on 2024-08-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0092_alter_operationday_operation_alter_operationitem_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationday",
            name="create_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AddField(
            model_name="operationday",
            name="day_number",
            field=models.PositiveIntegerField(default=1, verbose_name="Gün Numarası"),
        ),
        migrations.AddField(
            model_name="operationday",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Güncelleme Tarihi"
            ),
        ),
    ]
