# Generated by Django 4.2.11 on 2024-08-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0093_operationday_create_date_operationday_day_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivitylog",
            name="browser_info",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tarayıcı Bilgisi"
            ),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP Adresi"
            ),
        ),
    ]
