# Generated by Django 4.2.11 on 2024-08-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0095_alter_activitysuppliercities_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitycost",
            name="currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR"), ("RMB", "RMB")],
                default="TL",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="cost",
            name="currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR"), ("RMB", "RMB")],
                default="TL",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="guide",
            name="currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR"), ("RMB", "RMB")],
                default="TL",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR"), ("RMB", "RMB")],
                default="TL",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="museum",
            name="currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR"), ("RMB", "RMB")],
                default="TL",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="activity_payment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Hayır",
                max_length=20,
                verbose_name="Activite Ödemesi Bizde",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="guide_var",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Hayır",
                max_length=20,
                verbose_name="Rehber var mı?",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="hotel_payment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Hayır",
                max_length=20,
                verbose_name="Otel Ödemesi Bizde",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="museum_payment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Hayır",
                max_length=20,
                verbose_name="Müze Ödemesi Bizde",
            ),
        ),
        migrations.AlterField(
            model_name="salesprice",
            name="currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR"), ("RMB", "RMB")],
                default="TL",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="sell",
            name="currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR"), ("RMB", "RMB")],
                default="TL",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclecost",
            name="currency",
            field=models.CharField(
                choices=[("TL", "TL"), ("USD", "USD"), ("EUR", "EUR"), ("RMB", "RMB")],
                default="TL",
                max_length=3,
                verbose_name="Para Birimi",
            ),
        ),
    ]
