# Generated by Django 4.2.11 on 2024-08-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0096_alter_activitycost_currency_alter_cost_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationitem",
            name="activity_payment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=20,
                verbose_name="Activite Ödemesi Bizde",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="guide_var",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=20,
                verbose_name="Rehber var mı?",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="hotel_payment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=20,
                verbose_name="Otel Ödemesi Bizde",
            ),
        ),
        migrations.AlterField(
            model_name="operationitem",
            name="museum_payment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=20,
                verbose_name="Müze Ödemesi Bizde",
            ),
        ),
        migrations.AlterField(
            model_name="operationitemtemplate",
            name="activity_payment",
            field=models.CharField(
                choices=[("Evet", "Evet"), ("Hayır", "Hayır")],
                default="No",
                max_length=20,
                verbose_name="Activite Ödemesi Bizde",
            ),
        ),
        migrations.AlterField(
            model_name="operationitemtemplate",
            name="hotel_payment",
            field=models.CharField(
                choices=[("Evet", "Evet"), ("Hayır", "Hayır")],
                default="No",
                max_length=20,
                verbose_name="Otel Ödemesi Bizde",
            ),
        ),
        migrations.AlterField(
            model_name="operationitemtemplate",
            name="museum_payment",
            field=models.CharField(
                choices=[("Evet", "Evet"), ("Hayır", "Hayır")],
                default="No",
                max_length=20,
                verbose_name="Müze Ödemesi Bizde",
            ),
        ),
    ]
