# Generated by Django 4.2.11 on 2024-08-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0097_alter_operationitem_activity_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationitemtemplate",
            name="activity_payment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=20,
                verbose_name="Activite Ödemesi Bizde",
            ),
        ),
        migrations.AlterField(
            model_name="operationitemtemplate",
            name="hotel_payment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=20,
                verbose_name="Otel Ödemesi Bizde",
            ),
        ),
        migrations.AlterField(
            model_name="operationitemtemplate",
            name="museum_payment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=20,
                verbose_name="Müze Ödemesi Bizde",
            ),
        ),
    ]
