# Generated by Django 4.2.11 on 2024-10-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
                ("note", models.CharField(max_length=255, verbose_name="Note")),
            ],
        ),
    ]
