# Generated by Django 4.2.11 on 2024-10-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mixi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
                ("task", models.CharField(max_length=255, verbose_name="Task")),
                (
                    "complete",
                    models.BooleanField(default=False, verbose_name="Complete"),
                ),
            ],
        ),
    ]
