# Generated by Django 4.2.11 on 2024-10-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mixi", "0002_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shortcut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("url", models.CharField(max_length=255, verbose_name="Url")),
            ],
        ),
    ]
