# Generated by Django 4.2.11 on 2024-10-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mixi", "0003_shortcut"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
                ("name", models.CharField(max_length=100, verbose_name="Alarm Name")),
                ("time", models.TimeField(verbose_name="Alarm Time")),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Additional Info"
                    ),
                ),
            ],
        ),
    ]
