# Generated by Django 4.2.11 on 2024-10-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mixi", "0004_alarm"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarm",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
